[package]
name = "einsum"
version = "0.1.0"
authors = ["oracleofnj <jared.samet@aya.yale.edu>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
