[package]
name = "einsum"
version = "0.1.0"
authors = ["oracleofnj <jared.samet@aya.yale.edu>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
regex = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2"
ndarray = "0.12.1"
num-traits = "0.2.6"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 's'
